baseURL = "https://jetztinbonn.de"
languageCode = "de-DE"
pluralizeListTitles = false
title = "#jetztinbonn"
theme = "ananke"

DefaultContentLanguage = "de"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

[pagination]
  disableAliases = false
  pagerSize = 5			# Number of posts on posts page (sublevel)
  path = 'page'

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  body_classes = ""		# Changes headline colors (and keeps font "avenir")

  author = ""
  favicon = "/images/PrelimLogo.png"
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3	# Number of summaries on homepage (toplevel)

[[params.ananke_socials]]
name = "github"
url = "https://github.com/Anja-Pe"